language: d

d:
  - dmd

os:
  - linux

# Test step
script:
  - dub build --compiler=${DC}
  - dub build --root=test
  - cd bin && ./testsuite --show-logs

notifications:
  email:
    on_success: never
    on_failure: always

  irc:
    channels:
      - irc.freenode.net#beast-lang
    template:
      - "COMMIT: %{commit_subject} (%{commit})"
      - "RESULT: %{result}"